# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.TextField(db_index=True)),
                ('name', models.TextField(db_index=True)),
                ('trinity', models.TextField()),
                ('junction', models.TextField(null=True)),
                ('junction_description', models.TextField(null=True)),
                ('charisma', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('ap', models.IntegerField(null=True)),
                ('characters', models.TextField(null=True)),
                ('rarity', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deck_id', models.IntegerField(db_index=True)),
                ('position', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonvs.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('count', models.IntegerField(default=0)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimsonvs.Card')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('username', models.TextField(db_index=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(db_index=True)),
                ('date_joined', models.TimeField()),
                ('last_login', models.TimeField(null=True)),
                ('rank', models.IntegerField(default=0)),
                ('champion', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonvs.User'),
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonvs.User'),
        ),
    ]
