# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.TextField(db_index=True)),
                ('name', models.TextField(db_index=True)),
                ('trinity', models.TextField()),
                ('junction', models.TextField(null=True)),
                ('junction_function', models.TextField(null=True)),
                ('charisma', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('hp', models.IntegerField(null=True)),
                ('ap', models.IntegerField(null=True)),
                ('characters', models.TextField(null=True)),
                ('rarity', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deck_id', models.IntegerField(db_index=True)),
                ('card_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('card_id', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('username', models.TextField(db_index=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(db_index=True)),
                ('date_joined', models.TimeField()),
                ('last_login', models.TimeField(null=True)),
                ('first deck id', models.IntegerField(null=True)),
                ('second deck id', models.IntegerField(null=True)),
                ('third deck id', models.IntegerField(null=True)),
                ('rank', models.IntegerField(default=0)),
                ('champion', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
