# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonvs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='position',
            new_name='card_position',
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
