# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonvs', '0002_auto_20180118_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck_position',
        ),
    ]
